spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test_mybatis?serverTimezone=UTC
    druid:
      initial-size: 5
      max-active: 10

mybatis:
#  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.sq.domain
#  config-location: classpath:mybatis-config.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    use-generated-keys: true
logging:
  level:
    root: DEBUG